# 데이터분석 실습 : 영화 평점 데이터

    https://grouplens.org
    https://grouplens.org/datasets/movie/
    -readme.txt
    
    
UserID::MovieID::Rating::Timestamp

- UserIDs range between 1 and 6040 
- MovieIDs range between 1 and 3952
- Ratings are made on a 5-star scale (whole-star ratings only)
- Timestamp is represented in seconds since the epoch as returned by time(2)
- Each user has at least 20 ratings

시간 초단위, 6천명, 한사람당 최소 20개정도 평가

In [1]:
import numpy as np

# 구분자는 :: 이므로 delimiter = "::"

In [6]:
data = np.loadtxt('data/movie/ratings.dat',delimiter = "::",dtype = np.int64)
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [7]:
print(data.shape) # 행 , 열 

(1000209, 4)


In [10]:
# 1행 부터 20행까지 출력
print(data[0:21])
print(data[21:31,:2])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]]
[[   1  720]
 [   1 1270]
 [   1  527]
 [   1 2340]
 [   1   48]
 [   1 1097]
 [   1 1721]
 [   

In [12]:
# 전체 평점 평균
print(data[:,2].mean())
print(np.mean(data[:,2]))

3.581564453029317
3.581564453029317


# 하나의 열의 전체 데이터를 변수화 uniqe함수 사용 

In [59]:
# 사용자별 평점 평균
user_id = np.unique(data[:,0])
print(user_id.shape)

mean_value = []

# for문에서 user_id 한명당 data에서 그 사람의 행들만 가져오겠다.
#data_user 는 각 번호 사람들의 행들만 가져오게되는것.
for id in user_id:
    data_user = data[data[:,0] == id, : ]
    value = data_user[:,2].mean() #일단 한명의 평균 구하고
    mean_value.append([id,value]) #한명씩 id랑 values 형식으로 집어넣기
    
arr_mean_values = np.array(mean_value)
a = np.argamx(arr_mean_values[:,1])
print(arr_mean_values[282])
print("결과 : ",mean_value[:10])
print("최고 평점 : ",valueT.argmax())


TypeError: unhashable type: 'slice'

In [ ]:


print(np.argsort(arr_mean_values[:,1][::-1]))
# :: (Extended Slices)
arr = range(10)
list(arr)

list(arr[::2]) # 처음부터 끝까지 2간격으로 접근
list(arr[1::2]) # 인덱스가 1부터 2간격으로
list(arr[::-1]) #역순으로 접근
list(arr[::-2]) # 역순으로 2간격 접근
list(arr[3::-1]) #3q부터 역순으로 

In [23]:
# 사용자별 평점 평균 데이터를 파일로 저장
arr_mean_values = np.array(mean_value)
print(type(arr_mean_values))

#fmt = %.1f 소수점1자리만
np.savetxt("data/movie/id_rations.csv",arr_mean_values,delimiter = ",",fmt = "%.1f")

<class 'numpy.ndarray'>


In [24]:
print(valueT)

[5 3 3 ... 5 4 4]


# Pandas에서 제공하는 대표적인 자료구조
    1) Series
        값 + index
        - 인덱스의 길이는 데이터의 길이와 같아야한다.
        - 인덱스의 값을 인덱스 라벨(label)이라고하고 
        - 인덱스 라벨은 문자열, 날짜, 시간, 정수등도 가능
        
        판다스에서 value는 numpy의 ndrarray이다.
    2) DataFrame
    
    3) https://pandas.pydata.org
    

In [25]:
import pandas as pd
import numpy as np


In [26]:
s = pd.Series([95,34,28,24])
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0    95
1    34
2    28
3    24
dtype: int64


In [27]:
for i in enumerate([99,34,28,24]):
    print(i)

(0, 99)
(1, 34)
(2, 28)
(3, 24)


In [32]:
# 인덱스를 자유롭게 지정
s = pd.Series([99,34,28,24], index = ["서울","부산","인천","대구"])
print(s)
print("----------------")
print(s.index)
print(s.values) 
print("---------------")
s.index.name = "도시"
print(s)
print("-------------")
s.name = "인구"
print(s)

서울    99
부산    34
인천    28
대구    24
dtype: int64
----------------
Index(['서울', '부산', '인천', '대구'], dtype='object')
[99 34 28 24]
---------------
도시
서울    99
부산    34
인천    28
대구    24
dtype: int64
-------------
도시
서울    99
부산    34
인천    28
대구    24
Name: 인구, dtype: int64


In [36]:
# 인덱싱
print(s[1],s["부산"])
print(s[[0,3,1]],s[["서울","대구","부산"]])

34 34
도시
서울    99
대구    24
부산    34
Name: 인구, dtype: int64 도시
서울    99
대구    24
부산    34
Name: 인구, dtype: int64


# 시리즈와 딕셔너리 자료형
## 시리즈 객체는 라벨 값에 의해 인덱싱이 가능하므로 실질적으로 라벨 값을 키로 가지는 딕셔너리 자료형과 같다고 볼수 있다.

### 따라서 in연산도 가능하고 items메서드를 사용하면 for루프를 통해 각 언소의 키와 값을 접근할수도 있다.

### series변수.notnull() , true들만 보려면 S변수[S변수.notnull()]

In [37]:
"서울" in s

True

In [38]:
"대전" in s


False

# 인덱스 기반 연산
- 두 시리즈에 대한 연산을 하는 경우 인덱스가 같은 데이터에 대해서만 차이를 구한다.
- 같은 인덱스가 없으면 NaN (not a number)값을 가진다. 
- float자료형이된다

## NaN이 아닌 값을 구하려면 notnull 매서드를 사용한다.

In [43]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])

for k,v in s.items():
    print("%s = %d"%(k,v))
print("--------------")
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])
print(s2)
print("---------------")
ds = s- s2
print(ds)

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052
--------------
부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64
---------------
대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64


In [44]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [46]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

# 데이터의 갱신, 추가, 삭제


# 데이터 프레임 클래스
- 시리즈가 1차원 벡터 데이터에 행방향 (밑으로 쭉쭉 한줄씩) 인덱스를 붙인것이라면

## 데이터 프레임 클래스는 2차원 행렬 데이터에 인덱스를 붙인것과 비슷하다. 2차원이므로 각각의 행 데이터의 이름이 되는 행방향 인덱스 뿐 아니라 각각의 열 데이터의 이름이 되는 열방향 인덱스도 붙일수 있다. 

1. 우선 하나의 열이되는 데이터를 리스트나 일차원 배열을 준비한다.
2. 이 각각의 열에 대한 이름을 키로 가지는 딕셔너리를 만든다. 
3. 이데이터를 DataFrame 클래스 생성자에 넣는다. 동시에 열방향 인덱스는 columns 인수로 행방향 인덱스는 index인수로 지정한다. 

In [49]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [48]:
# 컬럼의 위치 변경
cols = ["지역","2015","2010","2005","2000","2010"]

In [50]:
print(df.values)
print(df.columns)
print(df.index)

[['수도권' 9904312 9631482 9762546 9853972 0.0283]
 ['경상권' 3448737 3393191 3512547 3655437 0.0163]
 ['수도권' 2890451 2632035 2517680 2466338 0.0982]
 ['경상권' 2466052 2431774 2456016 2473990 0.0141]]
Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')
Index(['서울', '부산', '인천', '대구'], dtype='object')


In [51]:
df["지역"]

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [52]:
df[["2010", "2015"]]


2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

# 행인덱싱 (행 = 슬라이싱)

In [53]:
df[:]

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

# 추가는 df["열명"] = 바꾸고싶게

#    del pd변수["열명"]

In [62]:
# 열 데이터의 갱신, 추가, 삭제
df["2010-2015 증가율"] = df["2010-2015 증가율"] *100
df

df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

del df["2010-2015 증가율"]
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

In [66]:
data = {
    "국어" : [80,90,70,30],
    "영어" : [90,70,60,40],
    "수학" : [90,60,80,70],
}

index = ["춘향","몽롱","향단","방자"]
df = pd.DataFrame(data, index=index)
print(df)

    국어  영어  수학
춘향  80  90  90
몽롱  90  70  60
향단  70  60  80
방자  30  40  70


In [67]:
netsong7 [15:09]

# 1. 인덱스를 춘향, 몽룡, 향단, 방자로 구성된 데이터프레임 df를 작성하시오.
data = {
    "국어" : [80,90,70,30],
    "영어" : [90,70,60,40],
    "수학" : [90,60,80,70],
}

index = ["춘향","몽롱","향단","방자"]
df = pd.DataFrame(data, index=index)
# 2. 모든 학생의 수학점수를 나타내시오


# 3. 모든 학생의 국어와 영어 점수를 나타내시오


# 4. 모든 학생의 각 과목 평균 점수를 새로운 열로 추가하시오.


# 5. 방자의 영어점수를 80점으로 수정하고 평균 점수도 다시 수정하시오


# 6. 춘향의 점수를 데이터 프레임으로 나타내시오


# 7. 향단의 점수를 Series로 나타내시오.

SyntaxError: invalid token (<ipython-input-67-a0a24580aa56>, line 1)

### 데이터 입출력

    pd.read_csv('파일명.csv')
    to_csv() : 
    read_table()


# 샘플 데이터로 사용할 csv파일을 %%writefile 매직 명령으로 만들어보자. 이 명령을 셀에 서술한대로 텍스트 파일을 만드는 명령이다.

### 폴더명/  경로설정도가능

In [70]:
%%writefile data/sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing data/sample1.csv


In [73]:
sample1 = pd.read_csv("data/sample1.csv", names = ["c1","c2","c3"])
sample1

c1     c2      c3
0  c1     c2      c3
1   1   1.11     one
2   2   2.22     two
3   3   3.33   three

# 특정 열을 인덱스로 저장하고 싶을 때 

pd.read_csv( 인자설정을 index_col = "하고싶은 열 이름" ) 

In [74]:
sample1 = pd.read_csv("data/sample1.csv", index_col = "c1")
sample1

c2      c3
c1              
1   1.11     one
2   2.22     two
3   3.33   three

# 샘플 데이터에대한 설명을 skipfows인수를 사용

### pd.read_csv( ....,skiprows = [a,b]) a이상 b이하  skip)

In [79]:
%%writefile data/sample4.txt
파일 제목 : sample4.txt
데이터 포맷의 설명:
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Overwriting data/sample4.txt


In [83]:
pd.read_csv('data/sample4.txt', skiprows=[0, 1])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [84]:
%%writefile data/sample5.csv
c1, c2, c3
1, 1.11, one
2, , two
누락, 3.33, three

Writing data/sample5.csv


# 특정값을 NaN으로 만들고 싶을때 
## pd.read_csv(na_values=['하고싶은값'])

In [87]:
df = pd.read_csv('data/sample5.csv',na_values=['누락'])
df

c1     c2      c3
0  1.0   1.11     one
1  2.0            two
2  NaN   3.33   three

In [88]:
%%writefile sample3.txt
c1        c2        c3        c4
0.179181 -1.538472  1.347553  0.43381
1.024209  0.087307 -1.281997  0.49265
0.417899 -2.002308  0.255245 -1.10515

Writing sample3.txt


In [89]:
pd.read_table('sample3.txt',sep='\s+')

c1        c2        c3       c4
0  0.179181 -1.538472  1.347553  0.43381
1  1.024209  0.087307 -1.281997  0.49265
2  0.417899 -2.002308  0.255245 -1.10515

In [93]:
df.to_csv("data/sample6.csv")
df.to_csv("data/sample7.txt",sep="|")
df.to_csv("data/sample8.csv",index=False,header=False)

# 고급 인덱싱 : Indexer
    loc : 라벨값 기반의 2차원 인덱싱
    iloc : 순서를 나타내는 정수 기반의 2차원 인덱싱
    ix
    at
    iat

In [98]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

# DataFrame 이 출력이 아니라 
# loc는 시리즈타입으로 나옴
### loc 인덱서를 사용하면서 인덱서를 하나만 넣으면 행을 선택한다. 
### 시리즈라서 상하로 길게 출력되기는 했지만 행을 가져오고있다.
-인덱스데이터의 슬라이스도 가능한다.
-기본인덱스의 못하는 기능이 가능

In [101]:
df[:"a"]
df.loc["a"]

df.loc["a":"b"]

A   B   C   D
a  10  11  12  13
b  14  15  16  17

In [102]:
# df[["a","c"]]
df.loc[["a","c"]]

A   B   C   D
a  10  11  12  13
c  18  19  20  21

# pd변수.컬럼명 >(크기비교)  True, False로 나옴

In [104]:
df.A>15
df.loc[df.A>15]

A   B   C   D
c  18  19  20  21

In [107]:
df['A']['b'] # 기본인덱싱
df.loc['b']['A'] #df.loc[행인덱스, 열 인덱스]

# 모든 행에 대해서 첫번째 행에 있는 값이 11 보다 작거나 같은 행의 컬럼을 추출
df.loc[: , df.loc["a",:]<=11 ]

A   B
a  10  11
b  14  15
c  18  19

In [108]:
### iloc 
df.iloc[0,1]
# df.iloc

11

# at, iat

In [109]:
%timeit df.loc["a","A"]
%timeit df.at["a","A"]

5.54 µs ± 57 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.03 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
